image: "ruby:2.5"

before_script:
  - ruby -v
  - apt-get update
  - curl -sL https://deb.nodesource.com/setup_10.x | bash -
  - apt-get install -y default-jre default-jdk nodejs
  - gem install metanorma-cli
  - npm install puppeteer
  - export NODE_PATH=$PWD/node_modules

build:
  script:
    - |
      source doctypes.env
      for template in $DOCTYPES
      do
        metanorma new test/$template --type $TYPE --doctype $template --template . --overwrite
        metanorma compile test/$template/document.adoc
      done      
  artifacts:
    paths:
      - "test/*/*.pdf"
      - "test/*/*.doc"
      - "test/*/*.html"
